# 网站信息
title:              "Black history of Drakeet"
description:        "branch: 永远的黑历史"

# 作者信息
author_name:        "drakeet"
author_email:       drakeet.me@gmail.com
twitter_username:   drak11t

# 网站设置
baseurl:            ""
permalink:          /:title
timezone:           Asia/Shanghai
encoding:           UTF-8

# 网站生成
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# 其他配置
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
